version: '3'
services:
  redis-search:
    container_name: redis-search
    image: redislabs/redisearch:latest
    restart: always

  search-api:
    container_name: search-api
    depends_on: ['redis-search-sync']
    build:
      context: ./nodejs-redis-search-example
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: always
    command: yarn test:dev
    environment:
      NODE_ENV: dev
      REDIS_HOST: redis-search
      REDIS_PORT: 6379
networks:
  internal:
    driver: bridge
